// End-to-end checks against the *built* app (vite preview). Run: npm run build && npm run e2e
import { chromium } from 'playwright-core'
import { spawn } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const PORT = 4190
const URL = `http://127.0.0.1:${PORT}/`
const tmp = mkdtempSync(path.join(tmpdir(), 'bmwg-e2e-'))
const fails = []
const ok = (c, m) => { if (c) console.log('  ok   ' + m); else { fails.push(m); console.log('  FAIL ' + m) } }
const step = m => console.log('\n# ' + m)

const server = spawn('npx', ['vite', 'preview', '--host', '127.0.0.1', '--port', String(PORT), '--strictPort'], { cwd: path.resolve(here, '..'), stdio: 'ignore' })
for (let i = 0; i < 40; i++) { try { if ((await fetch(URL)).ok) break } catch { /* wait */ } await new Promise(r => setTimeout(r, 250)) }

const browser = await chromium.launch({ executablePath: process.env.CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] })
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true, acceptDownloads: true })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
page.on('console', m => { if (m.type() === 'error' && !/favicon|Failed to load resource/.test(m.text())) errors.push(m.text()) })

const iso = off => { const d = new Date(); d.setDate(d.getDate() + off); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
const go = async hash => { await page.goto(URL + '#' + hash); await page.waitForTimeout(500) }
const text = async () => (await page.locator('body').innerText()).replace(/\s+/g, ' ')
const save = async () => { await page.getByRole('button', { name: /^Save/ }).click(); await page.locator('.sheet').waitFor({ state: 'detached', timeout: 8000 }) }
const lab = l => page.getByLabel(l, { exact: true })

try {
  step('1. first run: empty live garage, nothing fake')
  await go('/')
  await page.getByText('Welcome to your garage').waitFor({ timeout: 15000 })
  let t = await text()
  ok(/BMW X3/.test(t) && /xDrive35i/.test(t) && /F25 LCI/.test(t), 'vehicle profile (X3 xDrive35i F25 LCI) is shown from the central config')
  ok(!/Demo data/.test(t), 'live mode shows no demo banner')
  ok(/—\s*mi/.test(t) || /No odometer/.test(t) || /Add reading/.test(t), 'no mileage is invented before a reading exists')

  step('2. add mileage readings -> averages + projection')
  for (const [off, odo] of [[-28, '64200'], [-21, '64510'], [-14, '64900'], [-7, '65100'], [0, '65482']]) {
    await go('/add/mileage')
    await lab('Odometer').fill(odo)
    await lab('Date').fill(iso(off))
    await save()
  }
  await go('/')
  await page.waitForTimeout(600)
  t = await text()
  ok(/65,482/.test(t) && /ACTUAL/i.test(t), 'home shows 65,482 mi labelled ACTUAL')
  ok(/\+382/.test(t), 'last 7 days = +382 mi (from actual readings)')
  ok(/382\s*mi\/wk/.test(t), 'average = 382 mi/wk')
  ok(/65,864/.test(t) && /PROJECTED/i.test(t), 'projected next week = 65,864 labelled PROJECTED')
  await go('/add/mileage'); await lab('Odometer').fill('60000'); await lab('Date').fill(iso(0))
  ok(/Lower than/.test(await text()), 'an odometer lower than history is rejected with a reason')
  await page.getByRole('button', { name: 'Cancel' }).click()

  step('3. fuel: MPG only tank-to-tank')
  await go('/add/fuel')
  await lab('Date').fill(iso(-14)); await lab('Odometer').fill('64900'); await lab('Gallons').fill('12'); await lab('Price / gal').fill('4.05')
  await page.waitForTimeout(200)
  ok(/48\.6/.test(await page.locator('input[id]').evaluateAll(els => els.map(e => e.value).join(' '))), 'total auto-calculated from gallons x price (48.6)')
  ok(/Waiting for the next full tank|Baseline/.test(await text()), 'single fill-up previews as baseline (no MPG)')
  await save()
  await go('/logs/fuel')
  ok(/Waiting for next full tank/.test(await text()), '"Waiting for next full tank" shown after one fill')
  await go('/add/fuel')
  await lab('Date').fill(iso(-3)); await lab('Odometer').fill('65180'); await lab('Gallons').fill('13'); await lab('Price / gal').fill('4.12')
  ok(/21\.5 MPG/.test(await text()), 'live preview: 280 mi / 13.0 gal = 21.5 MPG')
  await save()
  await go('/logs/fuel')
  t = await text()
  ok(/21\.5\s*MPG/.test(t), 'fuel page current MPG 21.5')
  ok(/\$0\.\d{3}/.test(t), 'cost per mile shown')
  await page.getByPlaceholder(/Search station/).fill('nomatch-xyz')
  ok(/No fill-ups match/.test(await text()), 'fuel history search filters')

  step('4. shop, parts, service -> maintenance due calculation')
  await go('/add/shop'); await lab('Shop name').fill('Test BMW Service'); await lab('Phone').fill('555-0100'); await save()
  await go('/add/part'); await lab('Part name').fill('Test spark plugs'); await lab('Brand').fill('NGK'); await lab('Quantity').fill('6'); await lab('Unit price').fill('14'); await save()
  await go('/add/service')
  await lab('Title').fill('Oil change')
  await lab('Date').fill(iso(-10)); await lab('Mileage').fill('65000')
  await page.getByRole('button', { name: 'Engine Oil + Filter' }).click()
  await page.getByRole('button', { name: 'Part' }).click(); await page.getByLabel('Line description').fill('Oil + filter'); await page.getByLabel('Line cost').fill('74')
  await page.getByRole('button', { name: 'Labor' }).click()
  await page.getByLabel('Line cost').nth(1).fill('44')
  ok(/\$118\.00/.test(await text()), 'service total = 118.00 from line items')
  await save()
  await go('/logs/service')
  ok(/Oil change/.test(await text()) && /\$118\.00/.test(await text()), 'service appears in history')
  await go('/logs/maintenance')
  await page.getByRole('button', { name: /^Upcoming/ }).click()
  t = await text()
  ok(/Engine Oil \+ Filter/.test(t) && /Good/i.test(t), 'oil item is GOOD after logging service')
  await page.getByText('Engine Oil + Filter').first().click()
  await page.waitForTimeout(400)
  t = await text()
  ok(/72,500/.test(t), 'next due mileage = 65,000 + 7,500 = 72,500')
  ok(/How this is calculated/i.test(t), 'status is explained transparently')
  await go('/logs/maintenance'); await page.getByRole('button', { name: /^Recommended/ }).click()
  ok(/No record/i.test(await text()), 'items without history are "No record", not falsely due')

  step('5. mod + reminder + receipt photo')
  await go('/add/mod'); await lab('Name').fill('Black grilles'); await lab('Brand').fill('TestBrand'); await lab('Price').fill('129'); await save()
  await go('/car/mods'); ok(/Black grilles/.test(await text()), 'mod card created')
  await go('/add/reminder'); await lab('Reminder').fill('Tire rotation'); await lab('Due at mileage').fill('66000'); await save()
  await go('/reminders'); ok(/Tire rotation/.test(await text()) && /Due soon/i.test(await text()), 'mileage reminder: 518 mi away => Due soon')
  // 1x1 PNG receipt
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFUlEQVR42mP8z8BQz0AEYBxVSF+FAP5FDvcfRYWgAAAAAElFTkSuQmCC', 'base64')
  const pngPath = path.join(tmp, 'receipt.png'); writeFileSync(pngPath, png)
  await go('/add/receipt')
  await page.locator('input[type=file]:not([capture])').setInputFiles(pngPath)
  await page.locator('.thumb img').waitFor({ timeout: 8000 })
  await lab('Title').fill('Oil receipt'); await lab('Total').fill('118')
  await page.getByLabel('Attach to').selectOption({ label: /Service · Oil change/ }.constructor === RegExp ? undefined : undefined).catch(() => {})
  const opts = await page.getByLabel('Attach to').locator('option').allTextContents()
  const svcOpt = opts.find(o => /Service · Oil change/.test(o))
  ok(!!svcOpt, 'receipt can be attached to a service')
  await page.getByLabel('Attach to').selectOption({ label: svcOpt })
  await save()
  await go('/more/receipts')
  ok(/Oil receipt/.test(await text()) && /Linked/i.test(await text()), 'receipt stored + linked')
  await page.waitForTimeout(500)
  ok(await page.locator('.receipt-card img').first().evaluate(i => i.complete && i.naturalWidth > 0), 'receipt image renders from IndexedDB')
  await go('/logs/service')
  await page.getByText('Oil change').first().click(); await page.waitForTimeout(500)
  ok(/View receipt/i.test(await text()), 'service detail offers "View receipt"')

  step('6. persistence across reload')
  const snapshotText = async () => { await go('/'); await page.waitForTimeout(500); return text() }
  await page.reload(); await page.waitForTimeout(800)
  t = await snapshotText()
  ok(/65,482/.test(t), 'mileage survives reload')
  await go('/logs/fuel'); ok(/21\.5\s*MPG/.test(await text()), 'fuel + MPG survive reload')
  await go('/car/parts'); ok(/Test spark plugs/.test(await text()), 'parts survive reload')
  await go('/more/shops'); ok(/Test BMW Service/.test(await text()), 'shops survive reload')
  // new browsing context = "closing Safari and reopening": storage is per-profile, so reuse the same context
  const page2 = await ctx.newPage(); await page2.goto(URL + '#/car/mileage'); await page2.waitForTimeout(1200)
  ok(/65,482/.test((await page2.locator('body').innerText())), 'data visible in a fresh tab (new session)')
  await page2.close()

  step('7. export JSON')
  await go('/more/settings/data')
  const [dl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /Export backup/ }).click()])
  const backupPath = path.join(tmp, 'backup.json'); await dl.saveAs(backupPath)
  const backup = JSON.parse(readFileSync(backupPath, 'utf8'))
  ok(backup.app === 'bmw-garage' && backup.schema === 1, 'backup has app + schema version')
  ok(backup.data.mileage.length === 5 && backup.data.fuel.length === 2 && backup.data.services.length === 1 && backup.data.mods.length === 1 && backup.data.parts.length === 1, 'backup contains all records')
  ok(Object.keys(backup.blobs).length === 1, 'backup embeds the receipt photo')
  const [csvDl] = await Promise.all([page.waitForEvent('download'), page.getByText('Fuel', { exact: true }).first().click()])
  const csvPath = path.join(tmp, 'fuel.csv'); await csvDl.saveAs(csvPath)
  ok(readFileSync(csvPath, 'utf8').split('\r\n')[0].startsWith('date,odometer,gallons'), 'fuel CSV export')

  step('8. reset requires explicit confirmation, then restore from backup')
  await go('/more/settings')
  await page.getByRole('button', { name: /Erase all data/ }).click()
  const eraseBtn = page.getByRole('button', { name: 'Erase everything' })
  ok(await eraseBtn.isDisabled(), 'erase is disabled until RESET is typed')
  await page.locator('.dialog input').fill('reset')
  ok(await eraseBtn.isDisabled(), 'lowercase "reset" does not unlock it')
  await page.locator('.dialog input').fill('RESET'); await eraseBtn.click(); await page.waitForTimeout(800)
  await go('/'); await page.getByText('Welcome to your garage').waitFor({ timeout: 8000 })
  ok(true, 'garage erased -> empty state')
  await go('/more/settings/data')
  await page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath)
  await page.getByText('Import this backup?').waitFor()
  ok(/5 mileage readings/.test(await text()), 'import preview lists what is inside')
  await page.getByRole('button', { name: /Replace everything/ }).click()
  await page.getByRole('button', { name: 'Replace all data' }).click()
  await page.waitForTimeout(1200)
  await go('/'); await page.waitForTimeout(500)
  ok(/65,482/.test(await text()), 'import restored mileage')
  await go('/logs/fuel'); ok(/21\.5\s*MPG/.test(await text()), 'import restored fuel/MPG')
  await go('/more/receipts'); await page.waitForTimeout(600)
  ok(await page.locator('.receipt-card img').first().evaluate(i => i.complete && i.naturalWidth > 0), 'import restored receipt photo')
  await go('/more/settings/data')
  await page.locator('input[type=file][accept*="json"]').setInputFiles(path.join(tmp, 'receipt.png'))
  await page.waitForTimeout(500)
  ok(/not valid JSON|not a BMW Garage/.test(await text()), 'a bad file is rejected with a message')

  step('9. demo mode is isolated')
  await go('/more'); await page.getByRole('button', { name: 'Explore with demo data' }).click(); await page.waitForTimeout(2500)
  await go('/')
  ok(/Demo data/.test(await text()), 'demo banner visible')
  await go('/logs/fuel'); ok(/21\.5\s*MPG|MPG/.test(await text()) && /Example/.test(await text()), 'demo fuel log is example data')
  await go('/more'); await page.getByRole('button', { name: 'Back to my data' }).click(); await page.waitForTimeout(2000)
  await go('/'); ok(/65,482/.test(await text()) && !/Demo data/.test(await text()), 'back to real data, untouched')

  step('10. 3D viewer integration')
  await go('/car/3d')
  const frame = page.frameLocator('iframe[title*="3D"]')
  await frame.locator('canvas').waitFor({ timeout: 20000 })
  ok(true, '3D viewer canvas loaded inside the app')
  await page.getByRole('button', { name: 'Front' }).click(); await page.waitForTimeout(1300)
  await page.getByRole('tab', { name: 'Interior' }).click()
  ok(/Interior model not available/.test(await text()), 'Interior mode honestly reports no model')
  await page.getByRole('tab', { name: 'Details' }).click(); await page.getByRole('button', { name: 'Grille' }).click(); await page.waitForTimeout(1200)
  ok(await page.getByRole('button', { name: 'Reset camera' }).isVisible(), 'viewer controls present (reset/fullscreen)')

  step('11. PWA: manifest, service worker, offline')
  const mf = await page.evaluate(() => fetch('manifest.webmanifest').then(r => r.json()))
  ok(mf.display === 'standalone' && mf.name === 'BMW Garage' && mf.icons.length >= 3, 'manifest: standalone, name, icons')
  const html = await page.evaluate(() => fetch('./index.html').then(r => r.text()))
  ok(/apple-mobile-web-app-capable/.test(html) && /viewport-fit=cover/.test(html) && /apple-touch-startup-image/.test(html), 'iOS meta tags, splash screens + safe-area viewport')
  await go('/')
  const sw = await page.evaluate(async () => { const r = await navigator.serviceWorker.ready; return !!r.active })
  ok(sw, 'service worker active')
  await page.waitForTimeout(3000) // let precache finish
  await ctx.setOffline(true)
  await page.reload(); await page.waitForTimeout(1500)
  ok(/65,482/.test(await text()), 'OFFLINE: app shell loads and local data is intact')
  await go('/car/3d')
  await page.frameLocator('iframe[title*="3D"]').locator('canvas').waitFor({ timeout: 20000 })
  ok(true, 'OFFLINE: 3D viewer works')
  await ctx.setOffline(false)

  step('12. console health')
  ok(errors.length === 0, 'no console / page errors' + (errors.length ? ': ' + errors.slice(0, 3).join(' | ') : ''))
} catch (e) {
  fails.push('exception: ' + e.message)
  console.log('EXCEPTION', e.stack)
  await page.screenshot({ path: path.join(tmp, 'failure.png') }).catch(() => {})
  console.log('failure screenshot:', path.join(tmp, 'failure.png'))
} finally {
  await browser.close()
  server.kill()
}
console.log(`\n${fails.length ? 'FAILED' : 'PASSED'} (${fails.length} failure${fails.length === 1 ? '' : 's'})`)
process.exit(fails.length ? 1 : 0)
